### ISSUE TITLE
Make release 0.2

### ISSUE THREAD

**Issue by iqbal-lab** [AllTheBacteria/AllTheBacteria#20]
- [x] Run human decontamination, and create new release and high-quality data
- [x] Compress assemblies
- [x] Build compressed COBS indexes for mof-search==phylign
- [x] Test mof-search in house
- [ ] Test mof-search run by someone external
- [x] Make release
- [x] Withdraw release 0.1 because of the human contamination.

**Comment by aryakaul** [comment]
Hi! I'm interested in using AllTheBacteria for my project, but don't want to spend compute time analyzing v0.1 and the contaminated contigs. Any idea on a rough timeframe for v0.2? I would only need access to the compressed assemblies for my project.

**Comment by iqbal-lab** [comment]
Within 10 days definitely,  hopefully within 5

**Comment by martinghunt** [comment]
@aryakaul release 0.2 is available. For all future releases, we're hitting the release button on this GitHub repo, so people can get notified.

@iqbal-lab just noticed I don't think we did this? "Test mof-search run by someone external"

**Comment by iqbal-lab** [comment]
ah true, but both @shenwei356 and @Danderson123 have tested
