### ISSUE TITLE
xz security issue?

### ISSUE THREAD

**Issue by iqbal-lab** [AllTheBacteria/AllTheBacteria#22]
I haven't read this yet, but we should check whether it impacts our release of xz compressed assemblies

https://www.bleepingcomputer.com/news/security/red-hat-warns-of-backdoor-in-xz-tools-used-by-most-linux-distros/

**Comment by shenwei356** [comment]
The version we are using is not affected.

**Comment by iqbal-lab** [comment]
great, thanks for checking
