### ISSUE TITLE
how do we get notified of new releases?

### ISSUE THREAD

**Issue by ctb** [AllTheBacteria/AllTheBacteria#24]
I've subscribed to all the things on github, but now I hear v0.2 is out :). is there a mailing list I can sign up for? or somethin'?

my student, when I asked them how they knew: "Wait for everything to break and check why... That's what I did." 😆

**Comment by iqbal-lab** [comment]
To my mind it's not out, we have been transferring stuff to the FTP, and if people are looking they can see them appearing. But we've made no accouncement, and have not finished. 

My plan was to announce on microbio slack as soon as we had finished testing and put the files and README on the ftp. But that only works for people on that slack channel, which isn't great.  Maybe the simplest way to do it would be to put the README's/changelogs on the ftp, and trigger a "release" , so it is visible that way?

cc @martinghunt 

In terms of how far off is the release 
a) we have one file to move to the ftp
b) the README needs updating

So, it ought to happen tomorrow (today not possible i think)

**Comment by ctb** [comment]
cool!

I think triggering a "release" on github would be really nice. After all there's a button for it 😆 and then it notifies and so on.

**Comment by iqbal-lab** [comment]
(could add file listing and md5s)

**Comment by ctb** [comment]
thank you so much!
