### ISSUE TITLE
question about how samples were selected

### ISSUE THREAD

**Issue by ctb** [AllTheBacteria/AllTheBacteria#27]
I note that [SAMN00205533](https://www.ebi.ac.uk/ena/browser/view/SAMN00205533) is not in the assembly-stats.tsv file. It's isolate (culture) sequence from the E. coli Long Term Evolution Experiment. Is there a way I can find out why?

thanks!

**Comment by happykhan** [comment]
These are old. 

Instrument Platform:
ILLUMINA
Instrument Model:
Illumina Genome Analyzer

I'm trying to confirm but I think these are a  single end library

**Comment by ctb** [comment]
thanks!
