### ISSUE TITLE
AMR gene detection

### ISSUE THREAD

**Issue by iqbal-lab** [AllTheBacteria/AllTheBacteria#6]
1. (How handle genes that are intrinsic to a species)
2. What tool(s) to run - any reason not to replicate Grace's approach from https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001421 ? ("_AMR, heavy metal, and virulence genes were detected using AMRFinderPlus v3.6.15, with standard thresholds of minimum identity (curated cutoff if it exists and 0.9 otherwise) and default coverage of 0.5._")

**Comment by tefer0** [comment]
Abricate (https://github.com/tseemann/abricate)  can also be used for AMR and virulance gene detection. Mass screening of contigs for antimicrobial resistance or virulence genes. It comes bundled with multiple databases: NCBI, CARD, ARG-ANNOT, Resfinder, MEGARES, EcOH, PlasmidFinder, Ecoli_VF and VFDB.

**Comment by iqbal-lab** [comment]
Jane Hawkey and Dan Anderson running AMRFinder+

**Comment by iqbal-lab** [comment]
Done, released, and this is a dup issue
