### ISSUE TITLE
Pseudomonas-specific tools/analyses

### ISSUE THREAD

**Issue by iqbal-lab** [AllTheBacteria/AllTheBacteria#8]
Meeting Jo Fothergill in August to get ideas.

**Comment by iqbal-lab** [comment]
This is still quite open and undefined; spoke to Rachel Wheatley, need to follow up with more pseudomonas folk (eg Manchester crew, open to suggestions). MLST should happen across the board (all species) so this issue is only for things that are specific to pseudomonas.

**Comment by juliofdiaz** [comment]
I'm happy to contribute to the Pae analyses

**Comment by iqbal-lab** [comment]
Closing as too broad, will open specific ones
